site_name: OpenUnderstand Docs (v0.1.1dev)
site_url: https://m-zakeri.github.io/OpenUnderstand
repo_url: https://github.com/m-zakeri/OpenUnderstand
site_description: An open-source implementation of Understand Python API for Java language
site_author: Morteza Zakeri
copyright: Â© 2021-2022 OpenUnderstand project - IUST Reverse Engineering Research Laboratory

theme:
  name: material
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
          selection:
            members: True

nav:
    - Home: index.md
    - Entity kinds: entity_kinds.md
    - References kinds: reference_kinds.md
    - Source code metrics: source_code_metrics.md
    - Benchmarks: benchmarks.md
    - Development proposals:
        - Core entity-reference development: proposals/core_entity_reference_development.md
        - Core source code metrics development: proposals/core_source_code_metrics_development.md
        - Core code graphs and visualiztion development: proposals/core_code_graphs_development.md
        - Code review and bug fixing: proposals/code_review_and_bug_fixing.md
    - Analysis passes:
        - Call and Callby: reference_kinds/call_callby.md
    - Code graph and visulization:
        - Control flow graph: code_graphs/control_flow_graph.md
    - Tutorials: tutorials.md
    - Issue tracker: 'https://github.com/m-zakeri/OpenUnderstand/issues'